In [5]:
import pandas as pd
import numpy as np
import os
from tqdm import tqdm

In [6]:
base_dir = os.path.dirname(os.path.dirname(os.getcwd()))
data_dir = os.path.join(base_dir, 'data', 'processed_data', 'House2_full_shifted.csv')

In [7]:
reader = pd.read_csv(data_dir, chunksize = 10)

In [8]:
first_chunk = next(reader)

In [9]:
first_chunk

,Aggregate_t0,Aggregate_t1,Aggregate_t2,Aggregate_t3,Aggregate_t4,Aggregate_t5,Aggregate_t6,Aggregate_t7,Aggregate_t8,Aggregate_t9,...,Appliance1,Appliance2,Appliance3,Appliance4,Appliance5,Appliance6,Appliance7,Appliance8,Appliance9,dom
0,60.0,60.0,60.0,62.0,90.0,90.0,90.0,136.0,136.0,91.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17
1,60.0,60.0,60.0,60.0,62.0,90.0,90.0,90.0,136.0,136.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17
2,60.0,60.0,60.0,60.0,60.0,62.0,90.0,90.0,90.0,136.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17
3,62.0,60.0,60.0,60.0,60.0,60.0,62.0,90.0,90.0,90.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17
4,60.0,62.0,60.0,60.0,60.0,60.0,60.0,62.0,90.0,90.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17
5,60.0,60.0,62.0,60.0,60.0,60.0,60.0,60.0,62.0,90.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17
6,62.0,60.0,60.0,62.0,60.0,60.0,60.0,60.0,60.0,62.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17
7,59.0,62.0,60.0,60.0,62.0,60.0,60.0,60.0,60.0,60.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17
8,62.0,59.0,62.0,60.0,60.0,62.0,60.0,60.0,60.0,60.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17
9,60.0,62.0,59.0,62.0,60.0,60.0,62.0,60.0,60.0,60.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17

In [ ]:
reader = pd.read_csv(data_dir, chunksize = 100000)

In [13]:
next(reader)

,Aggregate_t0,Aggregate_t1,Aggregate_t2,Aggregate_t3,Aggregate_t4,Aggregate_t5,Aggregate_t6,Aggregate_t7,Aggregate_t8,Aggregate_t9,...,Appliance1,Appliance2,Appliance3,Appliance4,Appliance5,Appliance6,Appliance7,Appliance8,Appliance9,dom
0,60.0,60.0,60.0,62.0,90.0,90.0,90.0,136.0,136.0,91.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17
1,60.0,60.0,60.0,60.0,62.0,90.0,90.0,90.0,136.0,136.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17
2,60.0,60.0,60.0,60.0,60.0,62.0,90.0,90.0,90.0,136.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17
3,62.0,60.0,60.0,60.0,60.0,60.0,62.0,90.0,90.0,90.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17
4,60.0,62.0,60.0,60.0,60.0,60.0,60.0,62.0,90.0,90.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,63.0,63.0,62.0,63.0,63.0,63.0,63.0,63.0,63.0,63.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25
99996,63.0,63.0,63.0,62.0,63.0,63.0,63.0,63.0,63.0,63.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25
99997,63.0,63.0,63.0,63.0,62.0,63.0,63.0,63.0,63.0,63.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25
99998,63.0,63.0,63.0,63.0,63.0,62.0,63.0,63.0,63.0,63.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25
99999,62.0,63.0,63.0,63.0,63.0,63.0,62.0,63.0,63.0,63.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25

In [14]:
train_dir = os.path.join(base_dir, 'data', 'train', 'train_house2.csv')
test_dir = os.path.join(base_dir, 'data', 'test', 'test_house2.csv')

In [16]:
for chunk in tqdm(reader):
    chunk_train = chunk[((chunk['dom']-1)//7+1)%2==0]
    chunk_test = chunk[((chunk['dom']-1)//7+1)%2==1]
    chunk_train.drop(columns = ['dom'], inplace = True)
    chunk_test.drop(columns = ['dom'], inplace = True)
    chunk_train.to_csv(train_dir, mode = 'a', index = False)
    chunk_test.to_csv(test_dir, mode = 'a', index = False)

56it [12:30, 13.39s/it]